version: 0.2

env:
  parameter-store:
    SECRET_KEY_BASE: "/codepipeline/terraform-infra/Environment"

phases:
  init:
    commands:
      - echo test
      - terraform init -backend-config=config/backend.tf
      - echo $SECRET_KEY_BASE
artifacts:
  files:
    - '**/*'
