version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12.x
    commands:
      - npm install serverless -g
      - npm install
  build:
    commands:
      - echo test
artifacts:
  files:
    - '**/*'
  base-directory: .serverless
