version: 0.2

env:
  parameter-store:
    ENV: "/codepipeline/terraform-infra/Environment"

phases:
  install:
    commands:
      - echo test
      - terraform init -backend-config=config/backend.tf
  pre_build:
    on-failure: CONTINUE
    commands:
      - terraform workspace new $ENV | terraform workspace select $ENV
  build:
    commands:
      - terraform apply -auto-approve -var-file=config/$ENV.tfvars
artifacts:
  files:
    - '**/*'
