version: 0.2

env:
  parameter-store:
    ENV: "/codepipeline/terraform-infra/Environment"

phases:
  install:
    commands:
      - echo test
      - terraform init -backend-config=config/backend.tf
      - terraform workspace new $ENV
      - terraform workspaces list
artifacts:
  files:
    - '**/*'
